name       : libnetfilter_acct 
version    : 1.0.3 
release    : 1 
source     : 
    - http://www.netfilter.org/projects/libnetfilter_acct/files/libnetfilter_acct-1.0.3.tar.bz2 : 4250ceef3efe2034f4ac05906c3ee427db31b9b0a2df41b2744f4bf79a959a1a 
license    : LGPL-2.1 
component  : programming.library 
summary    : The libnetfilter_acct library provides the programming interface (API) for the extended accounting infrastructure. 
description: | 
    The libnetfilter_acct library provides the programming interface (API) 
    for the extended accounting infrastructure. 
builddeps  : 
    - pkgconfig(libmnl) 
setup      : | 
    %reconfigure 
build      : | 
    %make 
install    : | 
    %make_install 
